name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v2
      - name: Pull in dev.to posts
      - uses: Sergeypdf/Sergeypdf/blog-post-workflow@main
        with:
         # token: ${{ secrets.MY_GITHUB_PAT }}
          max_post_count: "3"
          feed_list: "https://dev.to/feed/sergeypdf"


